import React, { useEffect, useState } from 'react';
import { ClipboardList, RefreshCw, X, CalendarClock, UserRound, Layers3, FileText } from 'lucide-react';
import api from '../api/api';
import { useToast } from '../context/ToastContext';

type Audit = { id: number; username: string; module: string; action: string; entityType?: string; entityId?: number; details?: string; occurredAt: string };

const formatAuditDate = (value: string) => new Date(value).toLocaleString('es-DO', { dateStyle: 'long', timeStyle: 'short' });

const AuditPage: React.FC = () => {
  const [items, setItems] = useState<Audit[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedAudit, setSelectedAudit] = useState<Audit | null>(null);
  const toast = useToast();
  const load = async () => { try { setLoading(true); const { data } = await api.get('/audit?limit=200'); setItems(data); } catch { toast.error('No se pudo cargar la auditoría.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <div className="space-y-6 pt-2 pb-24">
    <div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-tangerine-50 text-tangerine-500"><ClipboardList size={24} /></div><div><h1 className="font-display text-2xl font-black text-sage-900">Auditoría</h1><p className="text-sm font-medium text-sage-500">Registro de actividad de la aplicación.</p></div></div><button onClick={() => void load()} className="rounded-xl bg-white p-3 text-sage-500 shadow-sm" title="Actualizar"><RefreshCw size={18} /></button></div>
    {loading ? <div className="py-10 text-center text-sm text-sage-500">Cargando actividad…</div> : items.length === 0 ? <div className="rounded-3xl bg-white p-8 text-center text-sm text-sage-500 shadow-sm">Todavía no hay eventos registrados.</div> : <div className="space-y-2">{items.map(item => <button type="button" key={item.id} onClick={() => setSelectedAudit(item)} className="w-full rounded-2xl border border-sage-100 bg-white p-4 text-left shadow-sm transition hover:border-tangerine-200"><div className="flex items-start justify-between gap-3"><div><p className="font-display font-black text-sage-900">{item.action}</p><p className="mt-1 text-xs font-bold text-sage-500">{item.module} · {item.username}{item.entityId ? ` · #${item.entityId}` : ''}</p></div><time className="max-w-[170px] text-right text-[10px] font-bold leading-relaxed text-sage-400">{formatAuditDate(item.occurredAt)}</time></div>{item.details && <p className="mt-3 truncate rounded-xl bg-sage-50 p-2.5 text-xs font-medium text-sage-600">{item.details}</p>}<p className="mt-2 text-[10px] font-black uppercase tracking-widest text-tangerine-500">Ver todos los detalles</p></button>)}</div>}
    {selectedAudit && <div className="fixed inset-0 z-50 flex items-end justify-center bg-sage-950/45 p-4 backdrop-blur-sm sm:items-center"><div role="dialog" aria-modal="true" className="w-full max-w-md space-y-5 rounded-[30px] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-widest text-tangerine-500">Detalle de auditoría</p><h2 className="mt-1 font-display text-xl font-black text-sage-900">{selectedAudit.action}</h2></div><button type="button" onClick={() => setSelectedAudit(null)} className="rounded-xl p-2 text-sage-400 hover:bg-sage-50" aria-label="Cerrar detalles"><X size={20} /></button></div><div className="space-y-3"><div className="flex items-center gap-3 rounded-2xl bg-sage-50 p-3"><UserRound size={18} className="text-tangerine-500" /><div><p className="text-[10px] font-black uppercase tracking-widest text-sage-400">Usuario</p><p className="text-sm font-bold text-sage-900">{selectedAudit.username}</p></div></div><div className="flex items-center gap-3 rounded-2xl bg-sage-50 p-3"><CalendarClock size={18} className="text-tangerine-500" /><div><p className="text-[10px] font-black uppercase tracking-widest text-sage-400">Fecha y hora</p><p className="text-sm font-bold text-sage-900">{formatAuditDate(selectedAudit.occurredAt)}</p></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-sage-50 p-3"><Layers3 size={17} className="mb-2 text-tangerine-500" /><p className="text-[10px] font-black uppercase tracking-widest text-sage-400">Módulo</p><p className="mt-1 text-sm font-bold text-sage-900">{selectedAudit.module}</p></div><div className="rounded-2xl bg-sage-50 p-3"><FileText size={17} className="mb-2 text-tangerine-500" /><p className="text-[10px] font-black uppercase tracking-widest text-sage-400">Registro</p><p className="mt-1 text-sm font-bold text-sage-900">{selectedAudit.entityType || 'General'}{selectedAudit.entityId ? ` #${selectedAudit.entityId}` : ''}</p></div></div><div className="rounded-2xl border border-sage-100 p-4"><p className="text-[10px] font-black uppercase tracking-widest text-sage-400">Detalles</p><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-relaxed text-sage-700">{selectedAudit.details || 'Sin detalles adicionales.'}</p></div></div><button type="button" onClick={() => setSelectedAudit(null)} className="w-full rounded-2xl bg-sage-900 py-3.5 font-black text-white">Cerrar</button></div></div>}
  </div>;
};
export default AuditPage;
